version: 2

sources:
  - name: splitwise_source
    meta:
      external_location: "s3://splitwise-raw/{name}/{name}.parquet"
    tables:
      - name: expense
      - name: groups
      - name: friends