name: "splitwise_transformations"
version: "1.0.0"
config-version: 2

profile: "splitwise"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  splitwise_transformations:
    groups: ["Flat 105"]
    purchase_types:
      swiggy:
        match: [".*swiggy.*"]
        non_match: [".*instamart.*"]
      instamart:
        match: [".*instamart.*"]
      supermarket:
        match: [".*supermarket.*"]
      bigbasket:
        match: [".*big.*", ".*basket.*"]

  "dbt_date:time_zone": "Asia/Kolkata"

models:
  splitwise_transformations:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: table
    marts:
      +schema: marts
      +materialized: table
