on:
  pull_request:
    branches:
    - WIP
  workflow_dispatch:
jobs:
  DBT-DOC-JOB:
    env:
        S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
        S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up dbt
        run: |
          pip install dbt-duckdb
          dbt --version
        working-directory: ./transform

      - name: Generate dbt Docs
        run: dbt docs generate
        working-directory: ./transform

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: transform/target # Change this to the directory where your dbt docs are generated
